<div class="l-nav fixed" ng-controller="menuController as menu">
		<nav class="top-bar" data-topbar role="navigation">
		  <ul class="title-area">
		    <li class="name">
		      <h1><?php print Html::link("#", "Servicios Especializados", "ng-click = 'menu.selectTab(1)'") ?></h1>
		    </li>
		     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
		    <li class="toggle-topbar menu-icon"><a><span>Menu</span></a></li>
		  </ul>

		  <section class="top-bar-section">
		    <!-- Right Nav Section -->
		    <ul class="right">
		      <li ng-class="{active: menu.isSelected(1)}"><?php print Html::link("#", "Sobre la empresa", "ng-click = 'menu.selectTab(1)'") ?></li>
		      <li ng-class="{active: menu.isSelected(2)}"><?php print Html::link("#portafolios", "Portafolios", "ng-click = 'menu.selectTab(2)'") ?></li>
		      <li ng-class="{active: menu.isSelected(3)}"><?php print Html::link("#blog", "Blogs", "ng-click = 'menu.selectTab(3)'") ?></li>
		      <li ng-class="{active: menu.isSelected(4)}"><?php print Html::link("#contact", "Contactanos", "ng-click = 'menu.selectTab(4)'") ?></li>
		      <li class="divider"></li>
		      <li><a href=""><i class="icon-fi-social-facebook"></i></a></li>
		      <li class="divider"></li>
		      <li><a href=""><i class="icon-fi-social-twitter"></i></a></li>
		      <li class="divider"></li>
		      <li><a href=""><i class="icon-fi-social-github"></i></a></li>
		      <!--
		      <li class="has-dropdown">
		        <a href="#">Right Button Dropdown</a>
		        <ul class="dropdown">
		          <li><a href="#">First link in dropdown</a></li>
		          <li class="active"><a href="#">Active link in dropdown</a></li>
		        </ul>
		      </li>
		    </ul>-->

		    <!-- Left Nav Section -->
		  </section>
		</nav>		
</div>